//
// Generated file, do not edit! Created by nedtool 5.0 from Segment.msg.
//

#ifndef __SEGMENT_M_H
#define __SEGMENT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Segment.msg:1</tt> by nedtool.
 * <pre>
 * packet Segment
 * {
 *     int source;
 *     int destination;//id du groupe de destination
 *     int num_seq;
 *     int msg_dhcp;
 *     int address[4];
 * 
 *     int MAJ_DHCP;//booleen si = 1 donc cest un msg de maj de la table dadressage envoyé par un server à un autre
 * 
 *     int adress_maj;//id du noeud auquel son adresse va etre maj dans un autre server
 *     int ss_reseau;//valeur du troisieme octet de ladresse (idf groupe)
 *     int idf_mac;//valeur du 4eme octet de ladresse (idf machine)
 * 
 *     int reply;
 * }
 * </pre>
 */
class Segment : public ::omnetpp::cPacket
{
  public:
    int source;
    int destination;
    int num_seq;
    int msg_dhcp;
    int address[4];
    int MAJ_DHCP;
    int adress_maj;
    int ss_reseau;
    int idf_mac;
    int reply;

  private:
    void copy(const Segment& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Segment&);

  public:
    Segment(const char *name=nullptr, int kind=0);
    Segment(const Segment& other);
    virtual ~Segment();
    Segment& operator=(const Segment& other);
    virtual Segment *dup() const {return new Segment(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getNum_seq() const;
    virtual void setNum_seq(int num_seq);
    virtual int getMsg_dhcp() const;
    virtual void setMsg_dhcp(int msg_dhcp);
    virtual unsigned int getAddressArraySize() const;
    virtual int getAddress(unsigned int k) const;
    virtual void setAddress(unsigned int k, int address);
    virtual int getMAJ_DHCP() const;
    virtual void setMAJ_DHCP(int MAJ_DHCP);
    virtual int getAdress_maj() const;
    virtual void setAdress_maj(int adress_maj);
    virtual int getSs_reseau() const;
    virtual void setSs_reseau(int ss_reseau);
    virtual int getIdf_mac() const;
    virtual void setIdf_mac(int idf_mac);
    virtual int getReply() const;
    virtual void setReply(int reply);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Segment& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Segment& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SEGMENT_M_H

